<a href="https://colab.research.google.com/github/Ziyan-spec/Data-Analysis-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Basics** **of** **Numpy**





### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types


### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [64]:
import numpy as np

In [8]:
#1D
a = np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [9]:
#2D
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
#3D
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
#data type
np.array([1,2,3],dtype= float)

array([1., 2., 3.])

In [12]:
#np.arange
b = np.arange(1,10, dtype=np.int32)
print(b.dtype)
print(b)
print(b.ndim)
print(b.shape)

int32
[1 2 3 4 5 6 7 8 9]
1
(9,)


In [13]:
#reshape
c = np.arange(1,13).reshape(3,4)
print(c.size)
print(c)
print(c.ndim)
print(c.shape)

12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.random.random((2,3))

array([[0.68785794, 0.08879602, 0.06428028],
       [0.09202076, 0.71133259, 0.44232155]])

In [17]:
print(a.dtype)
print(b.dtype)

int64
int32


In [18]:
e = a.astype(np.int32)
print(e.dtype)
print(e)

int32
[1 2 3]


# **Arithmetic** **Operations**

In [19]:
print(c)
#print(c*2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# **Relational** **Operators**

In [20]:
c > 4

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# **Vector** **Operation**





In [21]:
d = np.arange(1,13).reshape(3,4)
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
c + d

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

# **Array** **Functions**

In [23]:
a1 = np.arange(1,13).reshape(4,3)
a1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
#sum/min/max/product
print(np.sum(a1))
print(f"Max : {np.max(a1)}")
print(np.prod(a1))

78
Max : 12
479001600


In [25]:
print(np.prod(a1,axis=1))

[   6  120  504 1320]


In [26]:
#mean/median/std/var
np.var(a1, axis=1)

array([0.66666667, 0.66666667, 0.66666667, 0.66666667])

In [27]:
#trigonometric function
np.sin(a1)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292]])

In [28]:
#dot product
np.dot(a1,d)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200],
       [173, 206, 239, 272]])

In [29]:
#exponent and log
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [30]:
#floor/round/ceil
a2 = np.random.random((2,3))*100
print(a2)
print(f"Floor Vector : \n{np.floor(a2)}")
print(f"Round: \n {np.round(a2)}")
print(f"Ceil: \n {np.ceil(a2)}")

[[89.16937456 59.66405286 18.75190441]
 [53.6432132   0.80034646 49.11927017]]
Floor Vector : 
[[89. 59. 18.]
 [53.  0. 49.]]
Round: 
 [[89. 60. 19.]
 [54.  1. 49.]]
Ceil: 
 [[90. 60. 19.]
 [54.  1. 50.]]


# **Indexing** **and** **Slicing**

In [31]:
oneD = np.arange(10)
twoD = np.arange(1,13).reshape(3,4)
threeD = np.arange(27).reshape(3,3,3)

In [32]:
print(oneD)
print(oneD[-1])

[0 1 2 3 4 5 6 7 8 9]
9


In [33]:
print(twoD)
print(twoD[1,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7


In [34]:
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [35]:
threeD[1,0,1]

np.int64(10)

In [36]:
oneD

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
#slicing
oneD[2:5]

array([2, 3, 4])

In [38]:
twoD

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
twoD[:,2]

array([ 3,  7, 11])

In [40]:
twoD[2,:]

array([ 9, 10, 11, 12])

In [41]:
twoD[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [42]:
twoD[::2,1:4:2]

array([[ 2,  4],
       [10, 12]])

In [43]:
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [44]:
threeD[1,:,1]

array([10, 13, 16])

In [45]:
threeD[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# **Iteration**

In [46]:
oneD

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
for i in oneD:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [48]:
twoD

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
for i in twoD:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [50]:
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [51]:
for i in threeD:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [52]:
for i in np.nditer(threeD):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [53]:
#transpose
np.transpose(twoD)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [54]:
twoD.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [55]:
#ravel
twoD.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# **Stacking**

In [56]:
print(twoD.shape)
print(twoD)

(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [57]:
td = np.arange(12).reshape(3,4)
print(td)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [58]:
#horizontal
np.hstack((twoD,td))

array([[ 1,  2,  3,  4,  0,  1,  2,  3],
       [ 5,  6,  7,  8,  4,  5,  6,  7],
       [ 9, 10, 11, 12,  8,  9, 10, 11]])

In [59]:
#vertical
np.vstack((twoD,td))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# **Splitting**

In [60]:
newTwoD = twoD*3
newTwoD

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [61]:
#horizontal
np.hsplit(newTwoD,2)

[array([[ 3,  6],
        [15, 18],
        [27, 30]]),
 array([[ 9, 12],
        [21, 24],
        [33, 36]])]

In [62]:
np.hsplit(newTwoD,4)

[array([[ 3],
        [15],
        [27]]),
 array([[ 6],
        [18],
        [30]]),
 array([[ 9],
        [21],
        [33]]),
 array([[12],
        [24],
        [36]])]

In [63]:
#vertical
np.vsplit(newTwoD,3)

[array([[ 3,  6,  9, 12]]),
 array([[15, 18, 21, 24]]),
 array([[27, 30, 33, 36]])]